local state = require("data-explorer.state")

describe("state management", function()
	before_each(function()
		state.reset_state()
	end)

	it("gets all state", function()
		local all = state.get_all_state()
		assert.is_table(all)
		assert.is_table(all.files_metadata)
		assert.is_table(all.buffers)
		assert.is_table(all.windows)
		assert.is_nil(all.current_file)
		assert.is_nil(all.current_layout)
		assert.is_table(all.tbl_dimensions)
	end)

	it("sets and gets state value directly", function()
		state.set_state("current_file", nil, "foo.txt")
		assert.are.equal("foo.txt", state.get_state("current_file"))
	end)

	it("sets and gets state value by key", function()
		state.set_state("buffers", 1, "buffer1")
		assert.are.equal("buffer1", state.get_state("buffers", 1))
	end)

	it("resets a single state field", function()
		state.set_state("buffers", 1, "buffer1")
		state.reset_state("buffers")
		assert.are.same({}, state.get_state("buffers"))
	end)

	it("resets all state fields", function()
		state.set_state("buffers", 1, "buffer1")
		state.set_state("windows", 2, "window2")
		state.reset_state()
		assert.are.same({}, state.get_state("buffers"))
		assert.are.same({}, state.get_state("windows"))
	end)
end)
